<?php

// Requires the isolated storage configuration generated by acceptance.py.
if (!getenv('GORGE_TEST_FILE_URL') || !getenv('PHABRICATOR_ENV')) {
  throw new Exception('Run through worker/acceptance.py with isolated MySQL.');
}
require getenv('GORGE_TEST_ARCANIST_DIR').'/src/init/init-library.php';
phutil_load_library(dirname(__FILE__).'/../../../src');
if (getenv('GORGE_TEST_S3_CA')) { HTTPSFuture::setGlobalCABundleFromPath(getenv('GORGE_TEST_S3_CA')); }
if (getenv('GORGE_TEST_S3_ENDPOINT')) {
  id(new PhutilAWSS3Future())->addHeader('Host','127.0.0.1')
    ->setEndpoint(getenv('GORGE_TEST_S3_ENDPOINT'))
    ->setRegion('us-east-1')->setAccessKey(getenv('GORGE_TEST_S3_USER'))
    ->setSecretKey(new PhutilOpaqueEnvelope(getenv('GORGE_TEST_S3_PASSWORD')))
    ->setHTTPMethod('PUT')->setPath(getenv('GORGE_TEST_S3_BUCKET'))->resolve();
}
$root = dirname(__FILE__).'/../../..';
$case = id(new PhabricatorFileTestCase())
  ->setWorkingCopy(ArcanistWorkingCopyIdentity::newFromPath($root));
try { $case->willRunTestCases(array($case)); }
catch (CommandException $ex) {
  fwrite(STDERR, $ex->getStdout()."\n".$ex->getStderr());
  throw $ex;
}
try {
  $method = new ReflectionMethod('PhabricatorConfigSchemaSpec', 'getDetailsForDataType');
  $spec = new PhabricatorSearchSchemaSpec();
  foreach (array(8, 16, 32, 36, 64, 128, 512) as $size) {
    $details = $method->invoke($spec, 'varbytes'.$size);
    if ($details['type'] !== 'varbinary('.$size.')' || $details['bytes'] !== $size) {
      throw new Exception('Variable binary schema declaration mismatch.');
    }
  }
  if ($method->invoke($spec, 'bytes64')['type'] !== 'binary(64)') {
    throw new Exception('Legacy fixed-width binary declaration changed.');
  }
  $count = 0;
  foreach ($case->run() as $result) {
    if ($result->getResult() !== ArcanistUnitTestResult::RESULT_PASS) {
      throw new Exception($result->getName().': '.$result->getUserData());
    }
    $count++;
  }
  require dirname(__FILE__).'/../../../scripts/setup/lib/gorge_status_runtime.php';
  $report = gorge_status_runtime_report(true);
  if ($report['inventory']['files']['state'] !== 'observed' ||
      $report['inventory']['scheduler']['state'] !== 'observed') {
    throw new Exception('Unified report could not read the migrated fixture schema.');
  }
  foreach ($report['inventory']['persistentCapacity']['data'] as $table => $observation) {
    if ($observation['state'] !== 'observed' || !isset($observation['physicalDatabaseIdentity'])) {
      throw new Exception('Persistent table capacity unavailable: '.$table);
    }
  }
  $env = PhabricatorEnv::beginScopedEnv();
  $env->overrideEnvConfig('gorge.file.uri', getenv('GORGE_TEST_FILE_URL'));
  $env->overrideEnvConfig('gorge.file.token', getenv('GORGE_TEST_FILE_TOKEN'));
  $live = gorge_status_runtime_report(false);
  if ($live['services']['file']['uploadObservation']['state'] !== 'observed' ||
      $live['services']['file']['uploadObservation']['capabilities']['protocolVersion'] !== 1 ||
      !isset($live['uploadUsage']['logicalBytes'])) {
    throw new Exception('Unified report could not observe the real file backend.');
  }
  unset($env);
  echo 'Real file migration, reference and upload recovery checks passed: '.$count.".\n";
} finally {
  $case->didRunTestCases(array($case));
}
