<?php
// Test-only binary-safe backup/restore. Refuse every non-fixture database.
$db = new mysqli('127.0.0.1', 'root', getenv('GORGE_TEST_MYSQL_PASSWORD'), '',
  (int)getenv('GORGE_TEST_MYSQL_PORT'));
$names = array('gorge_paired_test', 'gorge_paired_test_metamta');
$action = $argv[1];
if ($action === 'init') {
  foreach ($names as $name) {
    if ($db->query("SHOW DATABASES LIKE '".$name."'")->num_rows) {
      throw new Exception('Refuse existing fixture database.');
    }
  }
  foreach ($names as $name) { $db->query('CREATE DATABASE `'.$name.'`'); }
  $db->select_db($names[0]);
  $sql = file_get_contents(getenv('GORGE_TEST_GORGE_DIR').'/go/internal/integrations/schema.sql');
  foreach (explode(';', $sql) as $statement) { if (trim($statement)) { $db->query($statement); } }
  $db->select_db($names[1]);
  $root = dirname(__FILE__).'/../../..';
  $db->query(str_replace('{$NAMESPACE}_metamta.', '', file_get_contents(
    $root.'/resources/sql/autopatches/20261007.metamta.01.gorgeinbound.sql')));
  preg_match('/CREATE TABLE `metamta_receivedmail` \(.*?;\n/s',
    file_get_contents($root.'/resources/sql/quickstart.sql'), $matches);
  $db->query(str_replace(array('{$CHARSET}', '{$COLLATE_TEXT}'),
    array('utf8mb4', 'utf8mb4_bin'), $matches[0]));
} else if ($action === 'sql') {
  $name = $argv[2]; if (!in_array($name, $names, true)) { throw new Exception('Unsafe database.'); }
  $db->select_db($name);
  $result = $db->query(stream_get_contents(STDIN));
  echo json_encode($result instanceof mysqli_result ? $result->fetch_all(MYSQLI_ASSOC) : array());
} else if ($action === 'backup') {
  $backup = array();
  foreach ($names as $name) {
    $db->select_db($name); $tables = $db->query('SHOW TABLES')->fetch_all();
    foreach ($tables as $table) {
      $name_table = $table[0];
      $ddl = $db->query('SHOW CREATE TABLE `'.$name_table.'`')->fetch_row()[1];
      $rows = $db->query('SELECT * FROM `'.$name_table.'`')->fetch_all();
      $rows = array_map(function($row) { return array_map(function($v) {
        return $v === null ? null : base64_encode($v);
      }, $row); }, $rows);
      $backup[$name][$name_table] = array('ddl'=>$ddl, 'rows'=>$rows);
    }
  }
  file_put_contents($argv[2], json_encode($backup)); chmod($argv[2], 0600);
} else if ($action === 'restore') {
  $backup = json_decode(file_get_contents($argv[2]), true);
  if (array_keys($backup) !== $names) { throw new Exception('Unsafe backup names.'); }
  foreach ($names as $name) {
    $db->query('DROP DATABASE `'.$name.'`'); $db->query('CREATE DATABASE `'.$name.'`');
    $db->select_db($name);
    foreach ($backup[$name] as $table) {
      $db->query($table['ddl']);
      foreach ($table['rows'] as $row) {
        $values = array_map(function($v) { return $v === null ? null : base64_decode($v, true); }, $row);
        // The fixture DDL is generated by SHOW CREATE TABLE, never external input.
        preg_match('/CREATE TABLE `([^`]+)`/', $table['ddl'], $match);
        $stmt = $db->prepare('INSERT INTO `'.$match[1].'` VALUES ('.implode(',', array_fill(0,count($values),'?')).')');
        $stmt->bind_param(str_repeat('s',count($values)), ...$values); $stmt->execute(); $stmt->close();
      }
    }
  }
} else if ($action === 'drop') {
  foreach ($names as $name) { $db->query('DROP DATABASE `'.$name.'`'); }
} else { throw new Exception('Unknown action.'); }
