CREATE TABLE {$NAMESPACE}_cache.gorge_gc_control (
 collectorID VARBINARY(64) NOT NULL PRIMARY KEY,
 owner VARBINARY(8) NOT NULL DEFAULT 'php',
 ownerEpoch BIGINT UNSIGNED NOT NULL DEFAULT 0,
 fence BIGINT UNSIGNED NOT NULL DEFAULT 0,
 policyJSON LONGTEXT NOT NULL,
 policyHash VARBINARY(64) NOT NULL,
 leaseOwner VARBINARY(64) NOT NULL DEFAULT '',
 leaseExpires BIGINT UNSIGNED NOT NULL DEFAULT 0,
 nextRun BIGINT UNSIGNED NOT NULL DEFAULT 0,
 cycleCutoff BIGINT UNSIGNED NOT NULL DEFAULT 0,
 deletedRows BIGINT UNSIGNED NOT NULL DEFAULT 0,
 lastSuccess BIGINT UNSIGNED NOT NULL DEFAULT 0,
 lastState VARBINARY(32) NOT NULL DEFAULT 'idle',
 failures INT UNSIGNED NOT NULL DEFAULT 0,
 lastError LONGTEXT NOT NULL
) ENGINE=InnoDB;
