CREATE TABLE {$NAMESPACE}_metamta.metamta_gorgeinboundreceipt (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 eventID VARCHAR(64) NOT NULL,
 digest VARCHAR(64) NOT NULL,
 state VARCHAR(16) NOT NULL,
 mailID INT UNSIGNED NULL,
 dateCreated INT UNSIGNED NOT NULL,
 dateModified INT UNSIGNED NOT NULL,
 UNIQUE KEY eventID(eventID)
) ENGINE=InnoDB;
